name: Deploy mdBook

on:
  pull_request:
  # push:
    #branches:
    #  - main  # or your default branch
    #paths:
    #  - 'docs/**'  # Only trigger when docs are updated

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Install mdbook-katex
        run: cargo install mdbook-katex

      - name: Build Book
        run: |
          cd docs  # Change to your docs directory
          mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book

